# Generated by Django 3.1.4 on 2020-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('V1', models.FloatField(blank=True, max_length=30, null=True)),
                ('V2', models.FloatField(blank=True, max_length=30, null=True)),
                ('V3', models.FloatField(blank=True, max_length=30, null=True)),
                ('V4', models.FloatField(blank=True, max_length=30, null=True)),
                ('V5', models.FloatField(blank=True, max_length=30, null=True)),
                ('V6', models.FloatField(blank=True, max_length=30, null=True)),
                ('V7', models.FloatField(blank=True, max_length=30, null=True)),
                ('V8', models.FloatField(blank=True, max_length=30, null=True)),
                ('V9', models.FloatField(blank=True, max_length=30, null=True)),
                ('V10', models.FloatField(blank=True, max_length=30, null=True)),
                ('V11', models.FloatField(blank=True, max_length=30, null=True)),
                ('V12', models.FloatField(blank=True, max_length=30, null=True)),
                ('V13', models.FloatField(blank=True, max_length=30, null=True)),
                ('V14', models.FloatField(blank=True, max_length=30, null=True)),
                ('V15', models.FloatField(blank=True, max_length=30, null=True)),
                ('V16', models.FloatField(blank=True, max_length=30, null=True)),
                ('V17', models.FloatField(blank=True, max_length=30, null=True)),
                ('V18', models.FloatField(blank=True, max_length=30, null=True)),
                ('V19', models.FloatField(blank=True, max_length=30, null=True)),
                ('V20', models.FloatField(blank=True, max_length=30, null=True)),
                ('V21', models.FloatField(blank=True, max_length=30, null=True)),
                ('V22', models.FloatField(blank=True, max_length=30, null=True)),
                ('V23', models.FloatField(blank=True, max_length=30, null=True)),
                ('V24', models.FloatField(blank=True, max_length=30, null=True)),
                ('V26', models.FloatField(blank=True, max_length=30, null=True)),
                ('V27', models.FloatField(blank=True, max_length=30, null=True)),
                ('V28', models.FloatField(blank=True, max_length=30, null=True)),
                ('Time', models.IntegerField()),
                ('Amount', models.FloatField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
