# Generated by Django 3.1.4 on 2020-12-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='V25',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
