# Generated by Django 3.1.4 on 2020-12-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_fraud_v25'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fraud',
        ),
    ]
